/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package convertidor;


import helpers.Cordoba;
import helpers.Dolar;
import helpers.Euro;
import helpers.Lempiras;
import java.awt.Color;



/**
 *
 * @author HP
 */
public class frmConvertidor extends javax.swing.JFrame {
    int cantidad;
    float moneda;
 
    
    /**
     * Creates new form frmConvertidor
     */
    public frmConvertidor() {
        initComponents();
        
           this.getContentPane().setBackground(Color.cyan);
           this.setLocationRelativeTo(null);
    
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCant = new javax.swing.JTextField();
        txtResul = new javax.swing.JTextField();
        cmbMonedas = new javax.swing.JComboBox<>();
        btnConvertir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblInfor = new javax.swing.JLabel();
        cmbDestino = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convertidor");

        txtCant.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtResul.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        cmbMonedas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbMonedas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "Euro", "Cordoba", "Lempira" }));

        btnConvertir.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/convertir.png"))); // NOI18N
        btnConvertir.setToolTipText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("CONVERTIDOR DE MONEDA");

        jLabel2.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 14)); // NOI18N
        jLabel2.setText("Moneda Origen");

        jLabel3.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 14)); // NOI18N
        jLabel3.setText("Ingrese Cantidad");

        jLabel4.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 14)); // NOI18N
        jLabel4.setText("Conversion");

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/salir.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/eliminar1.png"))); // NOI18N
        btnLimpiar.setToolTipText("Limpir");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblInfor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblInfor.setForeground(new java.awt.Color(0, 204, 51));

        cmbDestino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lempira", "Dolar", "Cordoba", "Euro" }));

        jLabel5.setFont(new java.awt.Font("CentSchbkCyrill BT", 1, 14)); // NOI18N
        jLabel5.setText("Moneda Destino");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/204-300x184.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(312, 312, 312))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbMonedas, 0, 266, Short.MAX_VALUE)
                                    .addComponent(cmbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCant)
                                    .addComponent(txtResul))
                                .addGap(226, 226, 226))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbMonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtResul, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblInfor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(81, 81, 81))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
       cantidad= Integer.parseInt(this.txtCant.getText());
       String x=(String)cmbMonedas.getSelectedItem();
       String y=(String)cmbDestino.getSelectedItem();
       Cordoba c=new Cordoba();
       Dolar d=new Dolar();
       Euro e=new Euro();
       Lempiras l=new Lempiras();
       
       if("Cordoba".equals(x) && "Lempira".equals(y)){      
        c.setResultado((float) 0.68, cantidad);
         this.txtResul.setText(String.valueOf(c.getResultado()));
         this.lblInfor.setText(c.getInfor());
       }
        if("Lempira".equals(x) && "Cordoba".equals(y)){     
         l.setResultado((float) 1.47, cantidad);
         this.txtResul.setText(String.valueOf(l.getResultado()));
           this.lblInfor.setText(l.getInfor());
       }
       
       if("Dolar".equals(x) && "Lempira".equals(y)){      
        d.setResultado((float) 24.4, cantidad);
         this.txtResul.setText(String.valueOf(d.getResultado()));
         this.lblInfor.setText(d.getInfor());
       }
       if("Lempira".equals(x) && "Dolar".equals(y)){    
        l.setResultado((float) 0.041, cantidad);
         this.txtResul.setText(String.valueOf(l.getResultado()));
         this.lblInfor.setText(l.getInfor());
       }
       
       if("Euro".equals(x)&& "Lempira".equals(y)){      
        e.setResultado((float) 26.90, cantidad);
        this.txtResul.setText(String.valueOf(e.getResultado()));
        this.lblInfor.setText(e.getInfor());
       }
       
       if("Lempira".equals(x)&& "Euro".equals(y)){    
        l.setResultado((float) 0.037, cantidad);
        this.txtResul.setText(String.valueOf(l.getResultado()));
        this.lblInfor.setText(l.getInfor());
       }
       if("Dolar".equals(x)&& "Euro".equals(y)){       
        d.setResultado((float) 0.91, cantidad);
        this.txtResul.setText(String.valueOf(d.getResultado()));
        this.lblInfor.setText(d.getInfor());
        }
       
       if("Euro".equals(x)&& "Dolar".equals(y)){       
        e.setResultado((float) 1.10, cantidad);
        this.txtResul.setText(String.valueOf(e.getResultado()));
        this.lblInfor.setText(e.getInfor());
        }
       if("Cordoba".equals(x)&& "Dolar".equals(y)){        
        c.setResultado((float) 0.028, cantidad);
        this.txtResul.setText(String.valueOf(c.getResultado()));
        this.lblInfor.setText(c.getInfor());
        }
       if("Dolar".equals(x)&& "Cordoba".equals(y)){    
        d.setResultado((float) 35.73, cantidad);
        this.txtResul.setText(String.valueOf(d.getResultado()));
        this.lblInfor.setText(d.getInfor());
        }
        if("Euro".equals(x)&& "Cordoba".equals(y)){
        e.setResultado((float) 39.42, cantidad);
        this.txtResul.setText(String.valueOf(e.getResultado()));
        this.lblInfor.setText(e.getInfor());
        }
        if("Cordoba".equals(x)&& "Euro".equals(y)){
        c.setResultado((float) 0.025, cantidad);
        this.txtResul.setText(String.valueOf(c.getResultado()));
        this.lblInfor.setText(c.getInfor());
        }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCant.setText(null);
        txtResul.setText(null);
        lblInfor.setText(null);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConvertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConvertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbMonedas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblInfor;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtResul;
    // End of variables declaration//GEN-END:variables
}
